### ISSUE TITLE
Please provide instruction how to build and test this project.

### ISSUE THREAD

**Issue by trsh** [AlerianEmperor/Voxel-Cone-Tracing#1]
As for now, no idea how to make this running.

**Comment by AlerianEmperor** [comment]
Right, this is OpenGL set up but I assume this is your first time so this is how:
1. Create an empty project, right click and select properties.
2. Click C++, choose "General", in "Additional Include Directories", paste the file path that contains the "gl" folder I provided in the project.  This step will include the header
3. Click Linker, choose "General", in "Additional Library Directories", paste the file path that contains the "Lib" folder I provided in the project.  This step will include the Library.
4. One Last Step is to copy the "assimp-vc140-mt.dll" to the folder that host your project file, if you skip this test, then Assimp will not working.

I don't provide the project file since I use C++14 and windows, so you have to build the project yourself because it's hardware dependent. After successfully compile the code, you will get the result similar to mine. 

I haven't update this project and others because they don't get much recognition. I get close to 40 clones weekly in this project alone but no star at all, same thing happen to Lux Renderer.

So I think it's better to keep new features in private repositories. And I will soon move to vulkan so there won't be new opengl coming out. But before that there will be SVGF, screen space ray tracing and better voxel cone tracing in Opengl, which produce way better results than this one. 

Thumb up and star my projects if you find this helpful. I am glad that you are interested in my projects, have a good day! happy coding!

**Comment by AlerianEmperor** [comment]
Right, this is OpenGL set up but I assume this is your first time so this is how:

1. Create an empty project, right click and select properties.
2.Click C++, choose "General", in "Additional Include Directories", paste the file path that contains the "gl" folder I provided in the project. This step will include the header
3.Click Linker, choose "General", in "Additional Library Directories", paste the file path that contains the "Lib" folder I provided in the project. This step will include the Library.
4. One Last Step is to copy the "assimp-vc140-mt.dll" to the folder that host your project file, if you skip this test, then Assimp will not working.
I don't provide the project file since I use C++14 and windows, so you have to build the project yourself because it's hardware dependent. After successfully compile the code, you will get the result similar to mine.

I haven't update this project and others because they don't get much recognition. I get close to 40 clones weekly in this project alone but no star at all, same thing happen to Lux Renderer.

So I think it's better to keep new features in private repositories. And I will soon move on to Vulkan so there won't be new Opengl coming out. But before that there will be SVGF, screen space ray tracing and better voxel cone tracing in Opengl, which produce way better results than this one.

Thumb up and star my projects if you find this helpful. I am glad that you are interested in my projects, have a good day! happy coding!

**Comment by AlerianEmperor** [comment]
Right, this is OpenGL set up but I assume this is your first time so this is how:

1.Create an empty project, right click and select properties.

2.Click C++, choose "General", in "Additional Include Directories", paste the file path that contains the "gl" folder I provided in the project. This step will include the header

3.Click Linker, choose "General", in "Additional Library Directories", paste the file path that contains the "Lib" folder I provided in the project. This step will include the Library.

4.One Last Step is to copy the "assimp-vc140-mt.dll" to the folder that host your project file, if you skip this test, then Assimp will not working.

I don't provide the project file since I use C++14 and windows, so you have to build the project yourself because it's hardware dependent. After successfully compile the code, you will get the result similar to mine.
I haven't update this project and others because they don't get much recognition. I get close to 40 clones weekly in this project alone but no star at all, same thing happen to Lux Renderer.

So I think it's better to keep new features in private repositories. And I will soon move on to Vulkan so there won't be new Opengl coming out. But before that there will be SVGF, screen space ray tracing and better voxel cone tracing in Opengl, which produce way better results than this one.

Thumb up and star my projects if you find this helpful. I am glad that you are interested in my projects, have a good day! happy coding!

**Comment by AlerianEmperor** [comment]
Right, this is OpenGL set up but I assume this is your first time so this is how:

  1.Create an empty project, right click and select properties.

  2.Click C++, choose "General", in "Additional Include Directories", paste the file path that contains the "gl" folder I provided in 
  the project. This step will include the header

  3.Click Linker, choose "General", in "Additional Library Directories", paste the file path that contains the "Lib" folder I provided 
  in the project. This step will include the Library.

  4.One Last Step is to copy the "assimp-vc140-mt.dll" to the folder that host your project file, if you skip this test, then Assimp 
  will not working.

I don't provide the project file since I use C++14 and windows, so you have to build the project yourself because it's hardware dependent. After successfully compile the code, you will get the result similar to mine.
I haven't update this project and others because they don't get much recognition. I get close to 40 clones weekly in this project alone but no star at all, same thing happen to Lux Renderer.

So I think it's better to keep new features in private repositories. And I will soon move on to Vulkan so there won't be new Opengl coming out. But before that there will be SVGF, screen space ray tracing and better voxel cone tracing in Opengl, which produce way better results than this one.

Thumb up and star my projects if you find this helpful. I am glad that you are interested in my projects, have a good day! happy coding!

**Comment by AlerianEmperor** [comment]
Right, this is OpenGL set up but I assume this is your first time so this is how:

1. Create an empty project, right click and select properties.
2. Click C++, choose "General", in "Additional Include Directories", paste the file path that contains the "gl" folder I provided in the project. This step will include the header
3. Click Linker, choose "General", in "Additional Library Directories", paste the file path that contains the "Lib" folder I provided
in the project. This step will include the Library.
4. One Last Step is to copy the "assimp-vc140-mt.dll" to the folder that host your project file, if you skip this test, then Assimp
will not working.

I don't provide the project file since I use C++14 and windows, so you have to build the project yourself because it's hardware dependent. After successfully compile the code, you will get the result similar to mine.
I haven't update this project and others because they don't get much recognition. I get close to 40 clones weekly in this project alone but no star at all, same thing happen to Lux Renderer.

So I think it's better to keep new features in private repositories. And I will soon move on to Vulkan so there won't be new Opengl coming out. But before that there will be SVGF, screen space ray tracing and better voxel cone tracing in Opengl, which produce way better results than this one.

Thumb up and star my projects if you find this helpful. I am glad that you are interested in my projects, have a good day! happy coding!

**Comment by AlerianEmperor** [comment]
Right, this is OpenGL set up but I assume this is your first time so this is how:

1. Create an empty project, right click and select properties.

2. Click C++, choose "General", in "Additional Include Directories", paste the file path that contains the "gl" folder I provided in the project. This step will include the header

3. Click Linker, choose "General", in "Additional Library Directories", paste the file path that contains the "Lib" folder I provided
in the project. This step will include the Library.

4. One Last Step is to copy the "assimp-vc140-mt.dll" to the folder that host your project file, if you skip this test, then Assimp
will not working.

I don't provide the project file since I use C++14 and windows, so you have to build the project yourself because it's hardware dependent. After successfully compile the code, you will get the result similar to mine.

I haven't update this project and others because they don't get much recognition. I get close to 40 clones weekly in this project alone but no star at all, same thing happen to Lux Renderer.

So I think it's better to keep new features in private repositories. And I will soon move on to Vulkan so there won't be new Opengl coming out. But before that there will be SVGF, screen space ray tracing and better voxel cone tracing in Opengl, which produce way better results than this one.

Thumb up and star my projects if you find this helpful. I am glad that you are interested in my projects, have a good day! happy coding!

**Comment by AlerianEmperor** [comment]
Right, this is OpenGL set up but I assume this is your first time so this is how:

1.Create an empty project, right click and select properties.

2.Click C++, choose "General", in "Additional Include Directories", paste the file path that contains the "gl" folder I provided in the project. This step will include the header

3.Click Linker, choose "General", in "Additional Library Directories", paste the file path that contains the "Lib" folder I provided
in the project. Next, choose "Input", then "Additional Dependencies", click in the blank space and type : glfw3.lib + enter button, assimp-vc140-mt.lib + enter button, glew32.lib + enter button, freeglut.lib + enter button. This step will include the Library.

4.One Last Step is to copy the "assimp-vc140-mt.dll" to the folder that host your project file, if you skip this test, then Assimp
will not working.

I don't provide the project file since I use C++14 and windows, so you have to build the project yourself because it's hardware dependent. After successfully compile the code, you will get the result similar to mine.

I haven't update this project and others because they don't get much recognition. I get close to 40 clones weekly in this project alone but no star at all, same thing happen to Lux Renderer.

So I think it's better to keep new features in private repositories. And I will soon move on to Vulkan so there won't be new Opengl coming out. But before that there will be SVGF, screen space ray tracing and better voxel cone tracing in Opengl, which produce way better results than this one.

Thumb up and star my projects if you find this helpful. I am glad that you are interested in my projects, have a good day! happy coding!

**Comment by AlerianEmperor** [comment]
Right, this is OpenGL set up but I assume this is your first time so this is how:

1. Create an empty project, right click and select properties.

2. Click C++, choose "General", in "Additional Include Directories", paste the file path that contains the "gl" folder I provided in the project. This step will include the header

3. Click Linker, choose "General", in "Additional Library Directories", paste the file path that contains the "Lib" folder I provided
in the project. Next, choose "Input", still in Linker, then "Additional Dependencies", click in the blank space and type : glfw3.lib + enter button, assimp-vc140-mt.lib + enter button, glew32.lib + enter button, freeglut.lib + enter button. This step will include the Library.

4. One Last Step is to copy the "assimp-vc140-mt.dll" to the folder that host your project file, if you skip this test, then Assimp
will not working.

I don't provide the project file since I use C++14 and windows, so you have to build the project yourself because it's hardware dependent. After successfully compile the code, you will get the result similar to mine.

I haven't update this project and others because they don't get much recognition. I get close to 40 clones weekly in this project alone but no star at all, same thing happen to Lux Renderer.

So I think it's better to keep new features in private repositories. And I will soon move on to Vulkan so there won't be new Opengl coming out. But before that there will be SVGF, screen space ray tracing and better voxel cone tracing in Opengl, which produce way better results than this one.

Thumb up and star my projects if you find this helpful. I am glad that you are interested in my projects, have a good day! happy coding!

**Comment by trsh** [comment]
@AlerianEmperor Hi!

You got my start for sure for helping out with this and sharing this project.  

The new project with SVGF, SSRT and better VCT, will it be hosted in this repository? Or another or private? What is the aprox ETA? I just think its a brilliant combination for real time graphics and would like to see how it is realized :)

**Comment by trsh** [comment]
Closing this as resolved for this time being.
